<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework.
 */
class AddPhonenumber extends Doctrine_Migration_Base
{
    public function migrate($direction)
    {
        $this->table($direction, 'migration_phonenumber', ['id' => ['type' => 'integer', 'length' => 20, 'autoincrement' => true, 'primary' => true], 'user_id' => ['type' => 'integer', 'length' => 2147483647], 'phonenumber' => ['type' => 'string', 'length' => 2147483647]], ['indexes' => [], 'primary' => [0 => 'id']]);
    }
}
