<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework.
 */
class DropProfile extends Doctrine_Migration_Base
{
    public function migrate($direction)
    {
        $direction = 'up' == $direction ? 'down' : 'up';
        $this->table($direction, 'migration_profile', ['id' => ['type' => 'integer', 'length' => 20, 'autoincrement' => true, 'primary' => true], 'name' => ['type' => 'string', 'length' => 255]], ['indexes' => [], 'primary' => [0 => 'id']]);
    }
}
